Check connection at startup breaking
Particular/NServiceBus.SqlServer pull request #709
Opened 2020-11-03 11:53 UTC by WilliamBZA

2020-11-05 11:10 UTC, tmasternak requested changes

2020-11-05 11:10 UTC, tmasternak commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
> +            if (!isDatabaseAccessible.Succeeded)
Could we make `TryOpenDatabaseConnection` and `TryEscalateToDistributedTransactions` two separate checks? This would remove the need for this if-statement.

2020-11-05 11:10 UTC, tmasternak commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
> +            settings.TryGet(SettingsKeys.IsNonDtcTransactionModeAllowed, out bool nonDtcTransactionModeAllowed);
Can we move this closer to the first usage?

2020-11-05 11:10 UTC, tmasternak commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
> +                    if (nonDtcTransactionModeAllowed)
Can we move this and the other if-statement in the `catch (SqlExcetpion sqlException)` block, outside of the `try-catch`  to prevent duplication?

2020-11-05 11:10 UTC, tmasternak commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportSettingsExtensions.cs
> +        public static TransportExtensions<SqlServerTransport> AllowNonDtcTransactionMode(this TransportExtensions<SqlServerTransport> transportExtensions)
How about `EnforceTransactionScopeMode`?

2020-11-05 11:42 UTC, WilliamBZA commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
> +            if (!isDatabaseAccessible.Succeeded)
The prestartupcheck only takes a single `Func`, so this is used to wrap the 2 separate checks into 1 for the `TransportReceieveInfrastructure` ctor.

2020-11-05 12:28 UTC, WilliamBZA commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportSettingsExtensions.cs
> +        public static TransportExtensions<SqlServerTransport> AllowNonDtcTransactionMode(this TransportExtensions<SqlServerTransport> transportExtensions)
It's not enforcing though, this setting is making it more permissable rather than less.

I changed it to `AllowNonDtcTransactionScopeMode` to make sure the TransactionScope part was included though.

2020-11-05 12:29 UTC, WilliamBZA commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
> +                    if (nonDtcTransactionModeAllowed)
Done

2020-11-05 12:29 UTC, WilliamBZA commented on src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
> +            settings.TryGet(SettingsKeys.IsNonDtcTransactionModeAllowed, out bool nonDtcTransactionModeAllowed);
Done

2020-11-06 10:05 UTC, tmasternak approved these changes

2020-11-06 13:51 UTC, mauroservienti approved these changes

2020-11-09 06:38 UTC, merged